[package]
name = "vach-cli"
version = "0.2.2"
edition = "2018"
authors = ["Jasper Fortuin <zeskeertwee@gmail.com>", "Newton Toto <nyachiengatoto@gmail.com>"]
description = "A command-line tool to work with .vach files"
license = "GPL-2.0"
repository = "https://github.com/zeskeertwee/virtfs-rs"
categories = [
	"command-line-utilities",
	"encoding",
	"game-development"
]
keywords = [
	"archive",
	"command-line",
	"vach",
	"assets",
	"game"
]
readme = "README.md"
include = [
	"src/*",
	"Cargo.toml",
	"../README.md"
]
[[bin]]
name = "vach"
path = "src/main.rs"

[dependencies]
indicatif = "0.16.2"
clap = "2.33.3"
anyhow = "1.0.44"
lazy_static = "1.4.0"
tabled = "0.3.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
vach = {	path = "../vach"	}
walkdir = "2.3.2"
bytesize = "1.1.0"
