[package]
name = "vach"
version = "0.2.1" # Make sure spec.txt and vach::VERSION constants are all synced up
edition = "2021"
authors = ["Jasper Fortuin <zeskeertwee@gmail.com>", "Newton Toto <nyachiengatoto@gmail.com>"]
description = "A simple archiving format, designed for storing assets in compact secure containers"
license = "GPL-2.0"
repository = "https://github.com/zeskeertwee/virtfs-rs"
categories = [
	"games",
	"compression"
]
keywords = [
	"archive",
	"filesystem",
	"compression",
	"game",
	"assets"
]
documentation = "https://docs.rs/vach"
readme = "../README.md"
include = [
	"Cargo.toml",
	"src/*",
	"../README.md"
]

[dependencies]
ed25519-dalek = "1.0.1"
lz4_flex = "0.9.0"
rand = "0.7.0"
aes-gcm-siv = "0.10.3"
